config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :deals
  #get 'home/index'
   get 'home/about'
  #root 'home#index'
  root 'deals#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :user
  validates :status , inclusion: { in: ['New', 'In Progress', 'Done'], message: "%{value} is not a valid status" }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :deals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit,:update,:destroy]
  # GET /deals or /deals.json
  def index
    @q = current_user.deals.ransack(params[:q])
    @deals = @q.result(distinct: true).paginate(page: params[:page], per_page: 20)
  end

  # GET /deals/1 or /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    #@deal = Deal.new
    @deal = current_user.deals.build
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals or /deals.json
  def create
    @deal = Deal.new(deal_params)
    # @deal = current_user.deals.build(deal_params)
    respond_to do |format|
      if @deal.save
        format.html { redirect_to deal_url(@deal), notice: "Deal was successfully created." }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1 or /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to deal_url(@deal), notice: "Deal was successfully updated." }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1 or /deals/1.json
  def destroy
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to deals_url, notice: "Deal was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def correct_user
    @deal = current_user.deals.find_by(id: params[:id])
    redirect_to deals_path, notice: "Not Authorized" if @deal.nil?
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def deal_params
      p params
      params.require(:deal).permit(:title, :description, :status, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/deals/_form.html.erb
<%= form_with(model: deal) do |form| %>
  <% if deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
        <% deal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%form.label :title %>
    <%= form.text_field :title, class:"form-control",placeholder:'Title' %>
  </div>

  <div class="field form-group">
    <%form.label :description %>
    <%= form.text_field :description, class:"form-control",placeholder:'Description' %>
  </div>

  <div class="field form-group">
    <%=form.label :status %>
    <% form.text_field :status %>
    <%= form.select :status, ['New', 'In Progress','Done'], class:"form-control"%>
  </div>

  <div class="field form-group">
    <%=form.label :user %>
    <%= form.collection_select :user_id, User.order(:email),:id, :email%>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-outline-info" %>
  </div>
<% end %>

app/views/deals/_search_form.html.erb
<%= search_form_for @q do |f| %>


  <%= f.label 'Search by title', style: 'margin: auto 1vw'%>
    <%= f.search_field :title_cont, placeholder: 'Title', style: 'margin: auto 1vw'%>
    <%= f.label "Filter by status ", style: 'margin: auto 1vw' %>
    <%= f.select :status_cont, ['New', 'In Progress', 'Done'], style: 'margin: auto 1vw' %>
  <%= f.submit "Search", style: 'margin: auto 1vw',class:"btn btn-outline-info btn-sm" %>
  <%= link_to 'Reset', deals_path,class:"btn btn-outline-dark btn-sm" %>


<% end %>

app/views/deals/edit.html.erb
<div class="card">
  <div class="card-header">
    <h4>Edit Deal</h4>
  </div>
  <div class="card-body">
    <%= render 'form', deal: @deal %>
    <% link_to 'Show', @deal %>
    <br/>
    <%= link_to 'Delete', @deal, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-outline-danger btn-sm' %>
    <%= link_to 'List', deals_path, class:"btn btn-outline-dark btn-sm" %>
  </div>
</div>

app/views/deals/index.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
<h1>Task List</h1>

  <%= render 'deals/search_form.html.erb' %>
<br/>
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @deals.each do |deal| %>
  <%if deal.user == current_user %>
      <tr>
        <td><%= link_to deal.title, deal %></td>
        <td><%= deal.description %></td>
        <td><%= deal.status %></td>

        <td><%= link_to 'Delete', deal, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-outline-danger btn-sm' %></td>
      </tr>
  <%end %>
    <% end %>
  </tbody>
</table>

  <%= will_paginate @deals, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>


<br/>

<% link_to 'New Deal', new_deal_path %>
  <br/>
  <% link_to 'Back', deals_path %>
<%else %>
  <div class="jumbotron">
    <h1 class="display-4">Case Manager</h1>
    <p class="lead">Control your affairs, conveniently!</p>
    <hr class="my-4">
    <p>To use this app, please Sign Up or Log in</p>
    <br/><br/>
  </div>
<%end %>

app/views/deals/new.html.erb
<div class="card">
  <div class="card-header">
    <h4>New Deal</h4>
  </div>
  <div class="card-body">
    <%= render 'form', deal: @deal %>
    <br/>
    <%= link_to 'List', deals_path, class:"btn btn-outline-dark btn-sm" %>
  </div>
</div>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>


<div class="jumbotron">
  <h1 class="display-4"><%= @deal.title %></h1>
  <p class="lead">  <%= @deal.description %></p>
  <hr class="my-4">
  <p>  <%= @deal.status %></p>
  <br/><br/>

  <%= link_to 'Edit', edit_deal_path(@deal), class:"btn btn-light"%>
  <%= link_to 'List', deals_path, class:"btn btn-outline-dark" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Task Manager', root_path, class:'navbar-brand' %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Add Deal", new_deal_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path,method: :delete, class:'nav-link' %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class:'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:'nav-link' %>
        </li>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class:'nav-link' %>
      </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/home/about.html.erb
<div class="jumbotron">
  <h1 class="display-4">Task Manager</h1>
  <p class="lead">Control your affairs, conveniently!</p>
  <hr class="my-4">
  <p>To use this app, please Sign Up or Log in</p>
  <br/><br/>
</div>

app/views/home/index.html.erb
<h3>Please Sign Up or Log in</h3>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <title>Task manager</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>

<%= render 'home/header' %>

<div class="container">
  <br/>
  <%= yield %>
</div>



<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

<!-- Option 2: jQuery, Popper.js, and Bootstrap JS
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
-->
</body>
</html>